/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RKinfotech.PMS;

import RKinfotech.Class.rkConnection;
import RKinfotech.Class.rkDatabase;
import RKinfotech.Class.rkValidation;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author rk
 */
public class RKClinical extends javax.swing.JInternalFrame {

    /**
     * Creates new form RKClinical
     */
    public RKClinical() {
        initComponents();
        con = rkConnection.rkConnection();
        mtHashMap = new HashMap<>();
        mtHashMap = db.DML("SELECT `ID`,`rkCode` FROM `rkmts`");
        mtHashMap.entrySet().forEach((e) -> {
            rkCodeMT.addItem((String) e.getKey());
        });
        db.rkAutoCompleted(new JComboBox[]{rkCodeMT});
        year = Integer.parseInt((String) rkYear.getSelectedItem());
        month = Integer.parseInt((String) rkMonth.getSelectedItem());
        
        conHashMap = new HashMap<>();
        int x = 0,y = 0;
        System.out.println(x+y);
        Object a,b,c,d;
        d = new Object();
        b=a=d;
        String asss = "Hello".substring(2,3);
        System.out.println(asss);
                   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this mtHashMap. The content of this method is always
 regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RKClinical = new javax.swing.JTabbedPane();
        rkMTStaff = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rkCodeMT = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rkNameMT = new javax.swing.JTextField();
        rkMedicinesMT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rkPlabMT = new javax.swing.JTextField();
        rkXrayMT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rkTotalMT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rkSaveMT = new javax.swing.JButton();
        rkYear = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        rkMonth = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        rkConStaff = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rkMedicinesContr = new javax.swing.JTextField();
        rkNameContr = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        rkTotalContr = new javax.swing.JTextField();
        rkXrayContr = new javax.swing.JTextField();
        rkPlabContr = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        rkSaveConStaff = new javax.swing.JButton();
        rkCodeCon1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rkYearCon = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        rkMonthCon = new javax.swing.JComboBox<>();
        rkSecStaff = new javax.swing.JPanel();
        rkNameSecu = new javax.swing.JTextField();
        rkMedicinesSecu = new javax.swing.JTextField();
        rkPlabSecu = new javax.swing.JTextField();
        rkXraySecu = new javax.swing.JTextField();
        rkTotalSecu = new javax.swing.JTextField();
        rkSaveSecStaff = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rkCodeSecu = new javax.swing.JTextField();
        rkDPSStaff = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rkMedicinesDSP = new javax.swing.JTextField();
        rkNameDSP = new javax.swing.JTextField();
        rkCodeDSP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rkTotalDSP = new javax.swing.JTextField();
        rkXrayDSP = new javax.swing.JTextField();
        rkPlabDSP = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rkSaveDSP = new javax.swing.JButton();
        rkNonRec = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rkMedicinesNonRec = new javax.swing.JTextField();
        rkNameNonRec = new javax.swing.JTextField();
        rkCodeNonRec = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rkTotalNonRec = new javax.swing.JTextField();
        rkXrayNonRec = new javax.swing.JTextField();
        rkPlabNonRec = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        rkSaveRec = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CLINICAL TREATMENT");

        jLabel4.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel4.setText("Code");

        rkCodeMT.setEditable(true);
        rkCodeMT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecte Code" }));
        rkCodeMT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkCodeMTItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel5.setText("Name");

        rkMedicinesMT.setText("00");

        jLabel6.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel6.setText("Medicines");

        jLabel7.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel7.setText("P-Lab");

        rkPlabMT.setText("00");

        rkXrayMT.setText("00");

        jLabel8.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel8.setText("X-Ray");

        rkTotalMT.setText("00");

        jLabel9.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel9.setText("Total");

        rkSaveMT.setText("Save");
        rkSaveMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkSaveMTActionPerformed(evt);
            }
        });

        rkYear.setEditable(true);
        rkYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        rkYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkMonthYearItemStateChanged(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel34.setText("Year");

        rkMonth.setEditable(true);
        rkMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        rkMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkMonthYearItemStateChanged(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel35.setText("Month");

        javax.swing.GroupLayout rkMTStaffLayout = new javax.swing.GroupLayout(rkMTStaff);
        rkMTStaff.setLayout(rkMTStaffLayout);
        rkMTStaffLayout.setHorizontalGroup(
            rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkMTStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rkMTStaffLayout.createSequentialGroup()
                        .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(88, 88, 88)
                        .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkNameMT)
                            .addComponent(rkCodeMT, 0, 176, Short.MAX_VALUE)))
                    .addGroup(rkMTStaffLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(53, 53, 53)
                        .addComponent(rkMedicinesMT))
                    .addGroup(rkMTStaffLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(88, 88, 88)
                        .addComponent(rkPlabMT))
                    .addGroup(rkMTStaffLayout.createSequentialGroup()
                        .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(88, 88, 88)
                        .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkTotalMT)
                            .addComponent(rkXrayMT)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rkMTStaffLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rkSaveMT, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rkMTStaffLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(22, 22, 22)
                        .addComponent(rkYear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(rkMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rkMTStaffLayout.setVerticalGroup(
            rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkMTStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rkYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(rkMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rkCodeMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkNameMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMedicinesMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rkPlabMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rkXrayMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkMTStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rkTotalMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rkSaveMT)
                .addContainerGap())
        );

        RKClinical.addTab("M & T Staff", rkMTStaff);

        jLabel29.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel29.setText("Emp Name");

        jLabel30.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel30.setText("Medicines");

        rkMedicinesContr.setText("00");
        rkMedicinesContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkMedicinesContrActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel31.setText("P-Lab");

        jLabel32.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel32.setText("X-Ray");

        rkTotalContr.setText("00");

        rkXrayContr.setText("00");

        rkPlabContr.setText("00");

        jLabel33.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel33.setText("Total");

        rkSaveConStaff.setText("Save");

        rkCodeCon1.setEditable(true);
        rkCodeCon1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecte Code" }));
        rkCodeCon1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkCodeCon1ItemStateChanged(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel36.setText("Code");

        jLabel37.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel37.setText("Year");

        rkYearCon.setEditable(true);
        rkYearCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        rkYearCon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkYearConrkMonthYearItemStateChanged(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel38.setText("Month");

        rkMonthCon.setEditable(true);
        rkMonthCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        rkMonthCon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkMonthConYearItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout rkConStaffLayout = new javax.swing.GroupLayout(rkConStaff);
        rkConStaff.setLayout(rkConStaffLayout);
        rkConStaffLayout.setHorizontalGroup(
            rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkConStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rkConStaffLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(48, 48, 48)
                        .addComponent(rkNameContr))
                    .addGroup(rkConStaffLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(53, 53, 53)
                        .addComponent(rkMedicinesContr))
                    .addGroup(rkConStaffLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(88, 88, 88)
                        .addComponent(rkPlabContr))
                    .addGroup(rkConStaffLayout.createSequentialGroup()
                        .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGap(88, 88, 88)
                        .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkTotalContr, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(rkXrayContr)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rkConStaffLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rkSaveConStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rkConStaffLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(88, 88, 88)
                        .addComponent(rkCodeCon1, 0, 181, Short.MAX_VALUE))
                    .addGroup(rkConStaffLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(22, 22, 22)
                        .addComponent(rkYearCon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rkMonthCon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rkConStaffLayout.setVerticalGroup(
            rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rkConStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rkYearCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(rkMonthCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(rkCodeCon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkNameContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMedicinesContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(rkPlabContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(rkXrayContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkConStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(rkTotalContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rkSaveConStaff)
                .addContainerGap())
        );

        RKClinical.addTab("Contractual Staff", rkConStaff);

        rkMedicinesSecu.setText("00");

        rkPlabSecu.setText("00");

        rkXraySecu.setText("00");

        rkTotalSecu.setText("00");

        rkSaveSecStaff.setText("Save");

        jLabel10.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel10.setText("Total");

        jLabel11.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel11.setText("X-Ray");

        jLabel12.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel12.setText("P-Lab");

        jLabel13.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel13.setText("Medicines");

        jLabel14.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel14.setText("Name");

        jLabel15.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel15.setText("Secu.Code");

        javax.swing.GroupLayout rkSecStaffLayout = new javax.swing.GroupLayout(rkSecStaff);
        rkSecStaff.setLayout(rkSecStaffLayout);
        rkSecStaffLayout.setHorizontalGroup(
            rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkSecStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rkSecStaffLayout.createSequentialGroup()
                        .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(49, 49, 49)
                        .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkNameSecu)
                            .addComponent(rkCodeSecu)))
                    .addGroup(rkSecStaffLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(53, 53, 53)
                        .addComponent(rkMedicinesSecu))
                    .addGroup(rkSecStaffLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(88, 88, 88)
                        .addComponent(rkPlabSecu))
                    .addGroup(rkSecStaffLayout.createSequentialGroup()
                        .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(88, 88, 88)
                        .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkTotalSecu, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(rkXraySecu)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rkSecStaffLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rkSaveSecStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rkSecStaffLayout.setVerticalGroup(
            rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkSecStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rkCodeSecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkNameSecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMedicinesSecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rkPlabSecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rkXraySecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkSecStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rkTotalSecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rkSaveSecStaff)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RKClinical.addTab("Security Staff", rkSecStaff);

        jLabel16.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel16.setText("DSP.Code");

        jLabel17.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel17.setText("Name");

        jLabel18.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel18.setText("Medicines");

        rkMedicinesDSP.setText("00");

        jLabel19.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel19.setText("P-Lab");

        jLabel20.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel20.setText("X-Ray");

        rkTotalDSP.setText("00");

        rkXrayDSP.setText("00");

        rkPlabDSP.setText("00");

        jLabel21.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel21.setText("Total");

        rkSaveDSP.setText("Save");

        javax.swing.GroupLayout rkDPSStaffLayout = new javax.swing.GroupLayout(rkDPSStaff);
        rkDPSStaff.setLayout(rkDPSStaffLayout);
        rkDPSStaffLayout.setHorizontalGroup(
            rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkDPSStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rkDPSStaffLayout.createSequentialGroup()
                        .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(53, 53, 53)
                        .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkNameDSP)
                            .addComponent(rkCodeDSP)))
                    .addGroup(rkDPSStaffLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(53, 53, 53)
                        .addComponent(rkMedicinesDSP))
                    .addGroup(rkDPSStaffLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(88, 88, 88)
                        .addComponent(rkPlabDSP))
                    .addGroup(rkDPSStaffLayout.createSequentialGroup()
                        .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(88, 88, 88)
                        .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkTotalDSP, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(rkXrayDSP)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rkDPSStaffLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rkSaveDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rkDPSStaffLayout.setVerticalGroup(
            rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkDPSStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(rkCodeDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkNameDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMedicinesDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rkPlabDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(rkXrayDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkDPSStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(rkTotalDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rkSaveDSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RKClinical.addTab("DPS Staff", rkDPSStaff);

        jLabel22.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel22.setText("Code");

        jLabel23.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel23.setText("Name");

        jLabel24.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel24.setText("Medicines");

        rkMedicinesNonRec.setText("00");

        jLabel25.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel25.setText("P-Lab");

        jLabel26.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel26.setText("X-Ray");

        rkTotalNonRec.setText("00");

        rkXrayNonRec.setText("00");

        rkPlabNonRec.setText("00");

        jLabel27.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel27.setText("Total");

        rkSaveRec.setText("Save");

        javax.swing.GroupLayout rkNonRecLayout = new javax.swing.GroupLayout(rkNonRec);
        rkNonRec.setLayout(rkNonRecLayout);
        rkNonRecLayout.setHorizontalGroup(
            rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rkNonRecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rkNonRecLayout.createSequentialGroup()
                        .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(88, 88, 88)
                        .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkNameNonRec)
                            .addComponent(rkCodeNonRec)))
                    .addGroup(rkNonRecLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(53, 53, 53)
                        .addComponent(rkMedicinesNonRec))
                    .addGroup(rkNonRecLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(88, 88, 88)
                        .addComponent(rkPlabNonRec))
                    .addGroup(rkNonRecLayout.createSequentialGroup()
                        .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(88, 88, 88)
                        .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkTotalNonRec, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(rkXrayNonRec)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rkNonRecLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rkSaveRec, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rkNonRecLayout.setVerticalGroup(
            rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rkNonRecLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rkCodeNonRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkNameNonRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMedicinesNonRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(rkPlabNonRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rkXrayNonRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rkNonRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(rkTotalNonRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rkSaveRec)
                .addContainerGap())
        );

        RKClinical.addTab("Non Recoverable", rkNonRec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RKClinical)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RKClinical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rkMedicinesContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkMedicinesContrActionPerformed
        // TODO add your handling mtHashMap here:
    }//GEN-LAST:event_rkMedicinesContrActionPerformed

    private void rkSaveMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkSaveMTActionPerformed
        try {
            if(rkMedicinesMT.getText().isEmpty())
                rkMedicinesMT.setText("00");
            if(rkPlabMT.getText().isEmpty())
                rkPlabMT.setText("00");
            if(rkXrayMT.getText().isEmpty())
                rkXrayMT.setText("00");
            
            if (rkSaveMT.getText().equals("Save")) {
                ps = con.prepareStatement("INSERT INTO `rkmts`(`rkCode`, `rkName`, `rkMedicine`, `rkPlab`, `rkXray`, `rkTotal`, `rkMonth`, `rkYear`) VALUES (?,?,?,?,?,?,?,?)");
                ps.setString(1, (String) rkCodeMT.getSelectedItem());
                ps.setString(2, rkNameMT.getText());
                ps.setString(3, rkMedicinesMT.getText());
                ps.setString(4, rkPlabMT.getText());
                ps.setString(5, rkXrayMT.getText());
                ps.setString(6, rkTotalMT.getText());
                ps.setString(7, (String) rkMonth.getSelectedItem());
                ps.setString(8, (String) rkYear.getSelectedItem());
                int count = ps.executeUpdate();
                if (count > 0) {
                    JOptionPane.showMessageDialog(this, "Recode Update Sucessfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            } else if (rkSaveMT.getText().equals("Update")) {
                ps = con.prepareStatement("UPDATE `rkmts` SET `rkName`=?,`rkMedicine`=?,`rkPlab`=?,`rkXray`=?,`rkTotal`=? WHERE ID = ?");
                ps.setString(1, rkNameMT.getText());
                ps.setInt(2, medicine + Integer.parseInt(rkMedicinesMT.getText()));
                ps.setInt(3, Plab + Integer.parseInt(rkPlabMT.getText()));
                ps.setInt(4, Xray + Integer.parseInt(rkXrayMT.getText()));
                ps.setInt(5, total + Integer.parseInt(rkTotalMT.getText()));
                ps.setString(6, (String) mtHashMap.get(rkCodeMT.getSelectedItem()));
                int count = ps.executeUpdate();
                if (count > 0) {
                    JOptionPane.showMessageDialog(this, "Recode Savrd Sucessfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, val.printError(e.getClass(), e.getMessage()));
        }
    }//GEN-LAST:event_rkSaveMTActionPerformed

    private void rkMonthYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkMonthYearItemStateChanged
        year = Integer.parseInt((String) rkYear.getSelectedItem());
        month = Integer.parseInt((String) rkMonth.getSelectedItem());
        rkMTS();
    }//GEN-LAST:event_rkMonthYearItemStateChanged

    private void rkCodeMTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkCodeMTItemStateChanged
        rkMTS();
    }//GEN-LAST:event_rkCodeMTItemStateChanged

    private void rkCodeCon1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkCodeCon1ItemStateChanged
        // TODO add your handling mtHashMap here:
    }//GEN-LAST:event_rkCodeCon1ItemStateChanged

    private void rkYearConrkMonthYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkYearConrkMonthYearItemStateChanged
        // TODO add your handling mtHashMap here:
    }//GEN-LAST:event_rkYearConrkMonthYearItemStateChanged

    private void rkMonthConYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkMonthConYearItemStateChanged
          
    }//GEN-LAST:event_rkMonthConYearItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane RKClinical;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> rkCodeCon1;
    private javax.swing.JTextField rkCodeDSP;
    private javax.swing.JComboBox<String> rkCodeMT;
    private javax.swing.JTextField rkCodeNonRec;
    private javax.swing.JTextField rkCodeSecu;
    private javax.swing.JPanel rkConStaff;
    private javax.swing.JPanel rkDPSStaff;
    private javax.swing.JPanel rkMTStaff;
    private javax.swing.JTextField rkMedicinesContr;
    private javax.swing.JTextField rkMedicinesDSP;
    private javax.swing.JTextField rkMedicinesMT;
    private javax.swing.JTextField rkMedicinesNonRec;
    private javax.swing.JTextField rkMedicinesSecu;
    private javax.swing.JComboBox<String> rkMonth;
    private javax.swing.JComboBox<String> rkMonthCon;
    private javax.swing.JTextField rkNameContr;
    private javax.swing.JTextField rkNameDSP;
    private javax.swing.JTextField rkNameMT;
    private javax.swing.JTextField rkNameNonRec;
    private javax.swing.JTextField rkNameSecu;
    private javax.swing.JPanel rkNonRec;
    private javax.swing.JTextField rkPlabContr;
    private javax.swing.JTextField rkPlabDSP;
    private javax.swing.JTextField rkPlabMT;
    private javax.swing.JTextField rkPlabNonRec;
    private javax.swing.JTextField rkPlabSecu;
    private javax.swing.JButton rkSaveConStaff;
    private javax.swing.JButton rkSaveDSP;
    private javax.swing.JButton rkSaveMT;
    private javax.swing.JButton rkSaveRec;
    private javax.swing.JButton rkSaveSecStaff;
    private javax.swing.JPanel rkSecStaff;
    private javax.swing.JTextField rkTotalContr;
    private javax.swing.JTextField rkTotalDSP;
    private javax.swing.JTextField rkTotalMT;
    private javax.swing.JTextField rkTotalNonRec;
    private javax.swing.JTextField rkTotalSecu;
    private javax.swing.JTextField rkXrayContr;
    private javax.swing.JTextField rkXrayDSP;
    private javax.swing.JTextField rkXrayMT;
    private javax.swing.JTextField rkXrayNonRec;
    private javax.swing.JTextField rkXraySecu;
    private javax.swing.JComboBox<String> rkYear;
    private javax.swing.JComboBox<String> rkYearCon;
    // End of variables declaration//GEN-END:variables
    private final rkValidation val = new rkValidation();
    private final rkDatabase db = new rkDatabase();
    private HashMap<Object, Object> mtHashMap,conHashMap,secHashMap,dspHashMap,recHashMap;
    private int year, month;
    private int Plab, Xray, total, medicine;
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    private void rkMTS(){
        try {
            ps = con.prepareStatement("SELECT * FROM `rkmts` WHERE `rkCode` = ? AND`rkMonth` = ? AND`rkYear` = ?");
            ps.setString(1, (String) rkCodeMT.getSelectedItem());
            ps.setInt(2, month);
            ps.setInt(3, year);
            rs = ps.executeQuery();

            if (rs.next()) {
                medicine = rs.getInt(4);
                Plab = rs.getInt(5);
                Xray = rs.getInt(6);
                total = rs.getInt(7);
                rkNameMT.setText(rs.getNString(3));
                rkNameMT.setEnabled(false);
                rkSaveMT.setText("Update");
            } else {
                medicine = Plab = Xray = total = 0;
                rkNameMT.setEnabled(true);
                rkSaveMT.setText("Save");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, val.printError(e.getClass(), e.getMessage()));
        }
    }
    

}
