/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RKinfotech.PMS;

import RKinfotech.Class.rkConnection;
import RKinfotech.Class.rkOpen;
import RKinfotech.Class.rkValidation;
import java.sql.*;

/**
 *
 * @author rk
 */
public class RKghclTotalRecord extends javax.swing.JInternalFrame {

    /**
     * Creates new form RKghclTotalRecord
     */
    public RKghclTotalRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        RKempJoin = new javax.swing.JPanel();
        rkMonth = new javax.swing.JComboBox<>();
        rkYear = new javax.swing.JComboBox<>();
        rkTotalRecord = new javax.swing.JButton();
        lblEmpJoin = new javax.swing.JLabel();
        RKempJoin3 = new javax.swing.JPanel();
        rkMonthEmp_Year = new javax.swing.JComboBox<>();
        rkYearEmp_Year = new javax.swing.JComboBox<>();
        rkTotalRecordEmp_Year = new javax.swing.JButton();
        lblEmpYear = new javax.swing.JLabel();
        RKempJoin1 = new javax.swing.JPanel();
        rkMonthCon_Join = new javax.swing.JComboBox<>();
        rkYearCon_Join = new javax.swing.JComboBox<>();
        rkTotalRecordCon_Join = new javax.swing.JButton();
        lblConJoin = new javax.swing.JLabel();
        RKempJoin2 = new javax.swing.JPanel();
        rkMonthCon_Year = new javax.swing.JComboBox<>();
        rkYearCon_Year = new javax.swing.JComboBox<>();
        rkTotalRecordCon_Year = new javax.swing.JButton();
        lblConYear = new javax.swing.JLabel();

        setTitle("Record");

        rkMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        rkYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));

        rkTotalRecord.setText("Display Total Record");
        rkTotalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkTotalRecordActionPerformed(evt);
            }
        });

        lblEmpJoin.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lblEmpJoin.setForeground(new java.awt.Color(255, 0, 255));
        lblEmpJoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpJoin.setText("00");

        javax.swing.GroupLayout RKempJoinLayout = new javax.swing.GroupLayout(RKempJoin);
        RKempJoin.setLayout(RKempJoinLayout);
        RKempJoinLayout.setHorizontalGroup(
            RKempJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rkTotalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RKempJoinLayout.createSequentialGroup()
                        .addComponent(rkMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rkYear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(lblEmpJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RKempJoinLayout.setVerticalGroup(
            RKempJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEmpJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(rkTotalRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Emp Join", RKempJoin);

        rkMonthEmp_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        rkYearEmp_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));

        rkTotalRecordEmp_Year.setText("Display Total Record");
        rkTotalRecordEmp_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkTotalRecordEmp_YearActionPerformed(evt);
            }
        });

        lblEmpYear.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lblEmpYear.setForeground(new java.awt.Color(255, 0, 255));
        lblEmpYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpYear.setText("00");

        javax.swing.GroupLayout RKempJoin3Layout = new javax.swing.GroupLayout(RKempJoin3);
        RKempJoin3.setLayout(RKempJoin3Layout);
        RKempJoin3Layout.setHorizontalGroup(
            RKempJoin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoin3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rkTotalRecordEmp_Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RKempJoin3Layout.createSequentialGroup()
                        .addComponent(rkMonthEmp_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rkYearEmp_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(lblEmpYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RKempJoin3Layout.setVerticalGroup(
            RKempJoin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoin3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMonthEmp_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkYearEmp_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(lblEmpYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rkTotalRecordEmp_Year)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Emp Year", RKempJoin3);

        rkMonthCon_Join.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        rkYearCon_Join.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));

        rkTotalRecordCon_Join.setText("Display Total Record");
        rkTotalRecordCon_Join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkTotalRecordCon_JoinActionPerformed(evt);
            }
        });

        lblConJoin.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lblConJoin.setForeground(new java.awt.Color(255, 0, 255));
        lblConJoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConJoin.setText("00");

        javax.swing.GroupLayout RKempJoin1Layout = new javax.swing.GroupLayout(RKempJoin1);
        RKempJoin1.setLayout(RKempJoin1Layout);
        RKempJoin1Layout.setHorizontalGroup(
            RKempJoin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rkTotalRecordCon_Join, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RKempJoin1Layout.createSequentialGroup()
                        .addComponent(rkMonthCon_Join, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rkYearCon_Join, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(lblConJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RKempJoin1Layout.setVerticalGroup(
            RKempJoin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMonthCon_Join, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkYearCon_Join, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(lblConJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rkTotalRecordCon_Join)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Con Join", RKempJoin1);

        rkMonthCon_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        rkYearCon_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));

        rkTotalRecordCon_Year.setText("Display Total Record");
        rkTotalRecordCon_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkTotalRecordCon_YearActionPerformed(evt);
            }
        });

        lblConYear.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lblConYear.setForeground(new java.awt.Color(255, 0, 255));
        lblConYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConYear.setText("00");

        javax.swing.GroupLayout RKempJoin2Layout = new javax.swing.GroupLayout(RKempJoin2);
        RKempJoin2.setLayout(RKempJoin2Layout);
        RKempJoin2Layout.setHorizontalGroup(
            RKempJoin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rkTotalRecordCon_Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RKempJoin2Layout.createSequentialGroup()
                        .addComponent(rkMonthCon_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rkYearCon_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(lblConYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RKempJoin2Layout.setVerticalGroup(
            RKempJoin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RKempJoin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RKempJoin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMonthCon_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkYearCon_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(lblConYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rkTotalRecordCon_Year)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Con Year", RKempJoin2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rkTotalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkTotalRecordActionPerformed
        try {
            if (rkMonth.getSelectedIndex() > 0 && rkYear.getSelectedIndex() > 0) {
                rkMonthEmpJoin = (String) rkMonth.getSelectedItem();
                rkYearEmpJoin = (String) rkYear.getSelectedItem();
                startDate = ""+rkYearEmpJoin + "-" + rkMonthEmpJoin + "-" + "01";
                endDate = ""+rkYearEmpJoin + "-" + rkMonthEmpJoin + "-" + "31";

                String qry = "SELECT COUNT(*) as count FROM `rkemp_joiningtimecheckup` WHERE `rkDOexam` BETWEEN '" + startDate + "' AND '" + endDate + "'";
                ps = cn.prepareStatement(qry);
                rs = ps.executeQuery();
                if(rs.next()){
                    lblEmpJoin.setText(rs.getInt("count")+"");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Select Month And Year after click display button"));
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Something is problme.", e.getMessage()));
        }
    }//GEN-LAST:event_rkTotalRecordActionPerformed

    private void rkTotalRecordCon_JoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkTotalRecordCon_JoinActionPerformed
        try {
            if (rkMonthCon_Join.getSelectedIndex() > 0 && rkYearCon_Join.getSelectedIndex() > 0) {
                rkMonthConJoin = (String) rkMonthCon_Join.getSelectedItem();
                rkYearConJoin = (String) rkYearCon_Join.getSelectedItem();
                startDate = ""+rkYearConJoin + "-" + rkMonthConJoin + "-" + "01";
                endDate = ""+rkYearConJoin + "-" + rkMonthConJoin + "-" + "31";

                String qry = "SELECT COUNT(*) as count FROM `rkcon_joiningtimecheckup` WHERE `rkDOexam` BETWEEN '" + startDate + "' AND '" + endDate + "'";
                ps = cn.prepareStatement(qry);
                rs = ps.executeQuery();
                    if(rs.next()){
                    lblConJoin.setText(rs.getInt("count")+"");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Select Month And Year after click display button"));
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Something is problme.", e.getMessage()));
        }
    }//GEN-LAST:event_rkTotalRecordCon_JoinActionPerformed

    private void rkTotalRecordCon_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkTotalRecordCon_YearActionPerformed
        try {
            if (rkMonthCon_Year.getSelectedIndex() > 0 && rkYearCon_Year.getSelectedIndex() > 0) {
                rkMonthConYear = (String) rkMonthCon_Year.getSelectedItem();
                rkYearConYear = (String) rkYearCon_Year.getSelectedItem();
                startDate = ""+rkYearConYear + "-" + rkMonthConYear + "-" + "01";
                endDate = ""+rkYearConYear + "-" + rkMonthConYear + "-" + "31";

                String qry = "SELECT COUNT(*) as count FROM `rkcon_yealycheckup` WHERE `rkDOexam` BETWEEN '" + startDate + "' AND '" + endDate + "'";
                ps = cn.prepareStatement(qry);
                rs = ps.executeQuery();
                    if(rs.next()){
                    lblConYear.setText(rs.getInt("count")+"");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Select Month And Year after click display button"));
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Something is problme.", e.getMessage()));
        }
    }//GEN-LAST:event_rkTotalRecordCon_YearActionPerformed

    private void rkTotalRecordEmp_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkTotalRecordEmp_YearActionPerformed
        try {
            if (rkMonthEmp_Year.getSelectedIndex() > 0 && rkYearEmp_Year.getSelectedIndex() > 0) {
                rkMonthEmpYear = (String) rkMonthEmp_Year.getSelectedItem();
                rkYearEmpYear = (String) rkYearEmp_Year.getSelectedItem();
                startDate = ""+rkYearEmpYear + "-" + rkMonthEmpYear + "-" + "01";
                endDate = ""+rkYearEmpYear + "-" + rkMonthEmpYear + "-" + "31";

                String qry = "SELECT COUNT(*) as count FROM `rkemp_yealycheckup` WHERE `rkDOexam` BETWEEN '" + startDate + "' AND '" + endDate + "'";
                ps = cn.prepareStatement(qry);
                rs = ps.executeQuery();
                    if(rs.next()){
                    lblEmpYear.setText(rs.getInt("count")+"");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Select Month And Year after click display button"));
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,rkValidation.printErrorStatic("Something is problme.", e.getMessage()));
        }
    }//GEN-LAST:event_rkTotalRecordEmp_YearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RKempJoin;
    private javax.swing.JPanel RKempJoin1;
    private javax.swing.JPanel RKempJoin2;
    private javax.swing.JPanel RKempJoin3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblConJoin;
    private javax.swing.JLabel lblConYear;
    private javax.swing.JLabel lblEmpJoin;
    private javax.swing.JLabel lblEmpYear;
    private javax.swing.JComboBox<String> rkMonth;
    private javax.swing.JComboBox<String> rkMonthCon_Join;
    private javax.swing.JComboBox<String> rkMonthCon_Year;
    private javax.swing.JComboBox<String> rkMonthEmp_Year;
    private javax.swing.JButton rkTotalRecord;
    private javax.swing.JButton rkTotalRecordCon_Join;
    private javax.swing.JButton rkTotalRecordCon_Year;
    private javax.swing.JButton rkTotalRecordEmp_Year;
    private javax.swing.JComboBox<String> rkYear;
    private javax.swing.JComboBox<String> rkYearCon_Join;
    private javax.swing.JComboBox<String> rkYearCon_Year;
    private javax.swing.JComboBox<String> rkYearEmp_Year;
    // End of variables declaration//GEN-END:variables
    private String rkMonthConJoin, rkMonthEmpJoin, rkMonthConYear, rkMonthEmpYear, rkYearConJoin, rkYearEmpJoin, rkYearConYear, rkYearEmpYear;
    String startDate, endDate;
    Connection cn = rkConnection.totalRecord();
    PreparedStatement ps = null;
    ResultSet rs = null;
}
