/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RKinfotech.PMS;

/**
 *
 * @author rk
 */
public class RKlogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form RKlogin
     */
    public RKlogin() {
        initComponents();
        setSize(597, 410);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RKusername = new javax.swing.JTextField();
        RKusername1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Login");
        getContentPane().setLayout(null);

        RKusername.setBackground(new java.awt.Color(51, 51, 51));
        RKusername.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        RKusername.setForeground(new java.awt.Color(255, 255, 255));
        RKusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RKusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RKusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RKusernameActionPerformed(evt);
            }
        });
        getContentPane().add(RKusername);
        RKusername.setBounds(180, 207, 250, 30);

        RKusername1.setBackground(new java.awt.Color(51, 51, 51));
        RKusername1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        RKusername1.setForeground(new java.awt.Color(255, 255, 255));
        RKusername1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RKusername1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RKusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RKusername1ActionPerformed(evt);
            }
        });
        getContentPane().add(RKusername1);
        RKusername1.setBounds(180, 130, 250, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton1.setText("Login");
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 287, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RKinfotech/Image/LoginImage1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 585, 379);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RKusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RKusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RKusernameActionPerformed

    private void RKusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RKusername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RKusername1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RKusername;
    private javax.swing.JTextField RKusername1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
