/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RKinfotech.PMS;

import RKinfotech.Class.rkConnection;
import RKinfotech.Class.rkDatabase;
import RKinfotech.Class.rkValidation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author rk
 */
public class RKPlantReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form RKPlantReport
     */
    public RKPlantReport() {
        initComponents();
        db.rkAutoCompleted(new JComboBox[]{rkYear, rkMonth});
        con = rkConnection.rkConnection();
        year = (String) rkYear.getSelectedItem();
        month = (String) rkMonth.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rkOfficers = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rkTechnitions = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rkContractW = new javax.swing.JTextField();
        rkTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rkNewCase = new javax.swing.JTextField();
        rkOldCase = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rkDressings = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rkMale = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rkFemale = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rkLTI = new javax.swing.JTextField();
        rkSave = new javax.swing.JButton();
        rkYear = new javax.swing.JComboBox<>();
        rkMonth = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("PLANT ANNUAL REPORT");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel6.setText("Month");

        jLabel7.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel7.setText("Year");

        jLabel8.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel8.setText("Officers");

        rkOfficers.setText("00");
        rkOfficers.setEnabled(false);
        rkOfficers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rkMasterTotalFocusLost(evt);
            }
        });
        rkOfficers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel9.setText("Technitions");

        rkTechnitions.setText("00");
        rkTechnitions.setEnabled(false);
        rkTechnitions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rkMasterTotalFocusLost(evt);
            }
        });
        rkTechnitions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel10.setText("Contract W.");

        rkContractW.setText("00");
        rkContractW.setEnabled(false);
        rkContractW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rkMasterTotalFocusLost(evt);
            }
        });
        rkContractW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        rkTotal.setEditable(false);
        rkTotal.setText("00");
        rkTotal.setEnabled(false);
        rkTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel11.setText("Total");

        jLabel12.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel12.setText("Old Case");

        jLabel13.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel13.setText("New Case");

        rkNewCase.setText("00");
        rkNewCase.setEnabled(false);
        rkNewCase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        rkOldCase.setText("00");
        rkOldCase.setEnabled(false);
        rkOldCase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel14.setText("Dressings");

        rkDressings.setText("00");
        rkDressings.setEnabled(false);
        rkDressings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel15.setText("Accident Case");

        jLabel16.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel16.setText("M");

        rkMale.setText("00");
        rkMale.setEnabled(false);
        rkMale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel17.setText("F");

        rkFemale.setText("00");
        rkFemale.setEnabled(false);
        rkFemale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel18.setText("LTI");

        rkLTI.setText("00");
        rkLTI.setEnabled(false);
        rkLTI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rkMasterKeyPressed(evt);
            }
        });

        rkSave.setText("New");
        rkSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkSaveActionPerformed(evt);
            }
        });

        rkYear.setEditable(true);
        rkYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        rkYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkYearYearMonthItemStateChanged(evt);
            }
        });

        rkMonth.setEditable(true);
        rkMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        rkMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkMonthYearMonthItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rkMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rkFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rkLTI, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rkDressings, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rkOldCase))
                                .addComponent(jLabel13)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rkYear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rkMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rkOfficers, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(rkTechnitions)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rkTotal)
                                        .addComponent(rkContractW)
                                        .addComponent(rkNewCase, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                                .addComponent(jLabel15)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rkSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rkYear)
                    .addComponent(rkMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rkOfficers)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkTechnitions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkContractW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkNewCase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkOldCase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkDressings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkMale)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkFemale)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkLTI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rkSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rkYearYearMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkYearYearMonthItemStateChanged
        try {
            year = (String) rkYear.getSelectedItem();
            month = (String) rkMonth.getSelectedItem();
            rkPredifineData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, val.printError(e.getClass(), e.getMessage(),getClass().getName()), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rkYearYearMonthItemStateChanged

    private void rkMonthYearMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkMonthYearMonthItemStateChanged
        try {
            year = (String) rkYear.getSelectedItem();
            month = (String) rkMonth.getSelectedItem();
            rkPredifineData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, val.printError(e.getClass(), e.getMessage(),getClass().getName()), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rkMonthYearMonthItemStateChanged

    private void rkMasterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rkMasterKeyPressed
        val.rkIsDigit(evt);
    }//GEN-LAST:event_rkMasterKeyPressed

    private void rkSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkSaveActionPerformed
        try {
            if (null != rkSave.getText()) {
                switch (rkSave.getText()) {
                    case "New":
                        rkPredifineData();
                        break;
                    case "Update":
                        rkUpdate();
                        break;
                    case "Save":
                        rkInsert();
                        break;
                    default:
                        break;
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, val.printError(e.getClass(), e.getMessage(),getClass().getName()), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rkSaveActionPerformed

    private void rkMasterTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rkMasterTotalFocusLost
        try {
            if (rkOfficers.getText().isEmpty()) {
                rkOfficers.setText("00");
            } else if (rkTechnitions.getText().isEmpty()) {
                rkTechnitions.setText("00");
            } else if (rkContractW.getText().isEmpty()) {
                rkContractW.setText("00");
            }
            String asn = String.valueOf(Integer.parseInt(rkOfficers.getText()) + Integer.parseInt(rkTechnitions.getText()) + Integer.parseInt(rkContractW.getText()));
            rkTotal.setText(asn);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, val.printError(e.getClass(), e.getMessage(),getClass().getName()), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rkMasterTotalFocusLost

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField rkContractW;
    private javax.swing.JTextField rkDressings;
    private javax.swing.JTextField rkFemale;
    private javax.swing.JTextField rkLTI;
    private javax.swing.JTextField rkMale;
    private javax.swing.JComboBox<String> rkMonth;
    private javax.swing.JTextField rkNewCase;
    private javax.swing.JTextField rkOfficers;
    private javax.swing.JTextField rkOldCase;
    private javax.swing.JButton rkSave;
    private javax.swing.JTextField rkTechnitions;
    private javax.swing.JTextField rkTotal;
    private javax.swing.JComboBox<String> rkYear;
    // End of variables declaration//GEN-END:variables
    private final rkValidation val = new rkValidation();
    private final rkDatabase db = new rkDatabase();

    private String year, month;
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    int rkRowID;

    private void rkUpdate() throws SQLException {
        ps = con.prepareStatement("UPDATE `rkplant` SET `rkPlantOfficer`=?,`rkPlantTechnition`=?,`rkPlantContract`=?,`rkPlantTotal`=?,`rkPlantNewCase`=?,`rkPlantOldCasel`=?,`rkPlantDressing`=?,`rkPlantMale`=?,`rkPlantFemale`=?,`rkPlantLTI`=?,`rkPlantMonth`=?,`rkPlantYear`=? WHERE `ID` = " + rkRowID);
        ps.setString(1, rkOfficers.getText());
        ps.setString(2, rkTechnitions.getText());
        ps.setString(3, rkContractW.getText());
        ps.setString(4, rkTotal.getText());
        ps.setString(5, rkNewCase.getText());
        ps.setString(6, rkOldCase.getText());
        ps.setString(7, rkDressings.getText());
        ps.setString(8, rkMale.getText());
        ps.setString(9, rkFemale.getText());
        ps.setString(10, rkLTI.getText());
        ps.setString(11, (String) rkMonth.getSelectedItem());
        ps.setString(12, (String) rkYear.getSelectedItem());
        int count = ps.executeUpdate();
        ps.close();

        if (count > 0) {
            JOptionPane.showMessageDialog(this, "Sucessfully update...", "Update", JOptionPane.INFORMATION_MESSAGE);
        }

        this.dispose();
    }

    private void rkInsert() throws SQLException {
        ps = con.prepareStatement("INSERT INTO `rkplant`(`rkPlantOfficer`, `rkPlantTechnition`, `rkPlantContract`, `rkPlantTotal`, `rkPlantNewCase`, `rkPlantOldCasel`, `rkPlantDressing`, `rkPlantMale`, `rkPlantFemale`, `rkPlantLTI`, `rkPlantMonth`, `rkPlantYear`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
        ps.setString(1, rkOfficers.getText());
        ps.setString(2, rkTechnitions.getText());
        ps.setString(3, rkContractW.getText());
        ps.setString(4, rkTotal.getText());
        ps.setString(5, rkNewCase.getText());
        ps.setString(6, rkOldCase.getText());
        ps.setString(7, rkDressings.getText());
        ps.setString(8, rkMale.getText());
        ps.setString(9, rkFemale.getText());
        ps.setString(10, rkLTI.getText());
        ps.setString(11, (String) rkMonth.getSelectedItem());
        ps.setString(12, (String) rkYear.getSelectedItem());
        int count = ps.executeUpdate();
        ps.close();
        if (count > 0) {
            JOptionPane.showMessageDialog(this, "Sucessfully Saved...", "Record Saved", JOptionPane.INFORMATION_MESSAGE);
        }

        this.dispose();
    }

    private void rkPredifineData() throws SQLException {
        ps = con.prepareStatement("SELECT * FROM `rkplant` WHERE `rkPlantMonth` =? AND `rkPlantYear` =?");
        ps.setString(1, month);
        ps.setString(2, year);
        rs = ps.executeQuery();
        if (rs.next()) {
            rkSave.setText("Update");
            rkRowID = rs.getInt(1);
            rkOfficers.setText(rs.getString(2));
            rkTechnitions.setText(rs.getString(3));
            rkContractW.setText(rs.getString(4));
            rkTotal.setText(rs.getString(5));
            rkNewCase.setText(rs.getString(6));
            rkOldCase.setText(rs.getString(7));
            rkDressings.setText(rs.getString(8));
            rkMale.setText(rs.getString(9));
            rkFemale.setText(rs.getString(10));
            rkLTI.setText(rs.getString(11));

            rkOfficers.setEnabled(true);
            rkTechnitions.setEnabled(true);
            rkContractW.setEnabled(true);
            rkNewCase.setEnabled(true);
            rkOldCase.setEnabled(true);
            rkDressings.setEnabled(true);
            rkMale.setEnabled(true);
            rkFemale.setEnabled(true);
            rkLTI.setEnabled(true);
            rs.close();
            ps.clearParameters();
            ps.close();
        } else {
            rkSave.setText("Save");
            rkOfficers.setEnabled(true);
            rkTechnitions.setEnabled(true);
            rkContractW.setEnabled(true);
            rkNewCase.setEnabled(true);
            rkOldCase.setEnabled(true);
            rkDressings.setEnabled(true);
            rkMale.setEnabled(true);
            rkFemale.setEnabled(true);
            rkLTI.setEnabled(true);

            rkOfficers.setText("00");
            rkTechnitions.setText("00");
            rkContractW.setText("00");
            rkTotal.setText("00");
            rkNewCase.setText("00");
            rkOldCase.setText("00");
            rkDressings.setText("00");
            rkMale.setText("00");
            rkFemale.setText("00");
            rkLTI.setText("00");
        }
    }
}
