/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RKinfotech.PMS;

import RKinfotech.Class.rkDatabase;
import RKinfotech.Class.rkValidation;
import java.awt.HeadlessException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author rk
 */
public class RKStockReg extends javax.swing.JInternalFrame {

    /**
     * Creates new form RKStockReg
     */
    public RKStockReg() {
        initComponents();
        rkbillItem = db.DML("SELECT `ID`,`ID` FROM `rkpurchase`");
        rkbillItem.entrySet().forEach((e) -> {
            rkBillNo.addItem((String) e.getKey());
        });

        db.rkAutoCompleted(new JComboBox[]{rkBillNo, rkMedicine});
        db.setRKcomboboxdb("SELECT `ID`, `rkMedicineName` FROM `rkmedicine`", rkMedicine);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rkMedicine = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rkBillNo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rkParticulars = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rkAmount = new javax.swing.JTextField();
        rkSave = new javax.swing.JButton();
        rkBatchNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rkExpDate = new com.toedter.calendar.JDateChooser();
        rkDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        rlStookIssued = new javax.swing.JTextField();

        setClosable(true);
        setForeground(new java.awt.Color(20, 20, 20));
        setIconifiable(true);
        setTitle("STOCK REGISTER");
        setToolTipText("");

        rkMedicine.setEditable(true);
        rkMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Medicine" }));
        rkMedicine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel1.setText("Name Of Medicine");

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel2.setText("Particulars");

        rkBillNo.setEditable(true);
        rkBillNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bill Number" }));
        rkBillNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rkItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel3.setText("Bill No");

        jLabel4.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel4.setText("Date");

        jLabel5.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel5.setText("Exp.Date");

        jLabel6.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel6.setText("Amount");

        rkSave.setText("Save");
        rkSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkSaveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel7.setText("Batch No.");

        jLabel8.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel8.setText("Quntities");

        rlStookIssued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlStookIssuedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rkAmount)
                            .addComponent(rkParticulars, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rkBillNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rkBatchNo)
                            .addComponent(rkExpDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rkDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(90, 90, 90)
                        .addComponent(rlStookIssued))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(rkMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rkSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rkParticulars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rkBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rkDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rkExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rkAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rlStookIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rkSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rkSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkSaveActionPerformed
        try {
            java.util.Date dt = rkDate.getDate();
            String rkStart = (dt.getYear() + 1900) + "-" + (dt.getMonth() + 1) + "-" + dt.getDate();
            rktxtDate.setText(rkStart);

            java.util.Date dt1 = rkExpDate.getDate();
            String rkexDate = (dt1.getYear() + 1900) + "-" + (dt1.getMonth() + 1) + "-" + dt1.getDate();
            rktxtExpDate.setText(rkexDate);

            int count = db.DML("INSERT INTO `rkstock`(`rkStockName`, `rkStockParticular`, `rkStockBatchNo`, `rkStockDate`, `rkStockExpDate`, `rkStockAmount`,`rkStockQuntities`,`rkStockBillNo`) VALUES (?,?,?,?,?,?,?,?)", new JTextField[]{rkMedicineName, rkParticulars, rkBatchNo, rktxtDate, rktxtExpDate, rkAmount,rlStookIssued, rktxtBillNo,});

            if (count > 0) {
                JOptionPane.showMessageDialog(this, "Record Saved Successfully.....", "Saved Record", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, val.printError(e.getClass(), e.getMessage(), getClass().getName()), "Error", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_rkSaveActionPerformed

    private void rkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rkItemStateChanged
        try {
            rkMedicineName.setText((String) rkMedicine.getSelectedItem());
            rktxtBillNo.setText((String) rkbillItem.get(rkBillNo.getSelectedItem()));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_rkItemStateChanged

    private void rlStookIssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlStookIssuedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlStookIssuedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField rkAmount;
    private javax.swing.JTextField rkBatchNo;
    private javax.swing.JComboBox<String> rkBillNo;
    private com.toedter.calendar.JDateChooser rkDate;
    private com.toedter.calendar.JDateChooser rkExpDate;
    private javax.swing.JComboBox<String> rkMedicine;
    private javax.swing.JTextField rkParticulars;
    private javax.swing.JButton rkSave;
    private javax.swing.JTextField rlStookIssued;
    // End of variables declaration//GEN-END:variables
    rkDatabase db = new rkDatabase();
    rkValidation val = new rkValidation();
    JTextField rkMedicineName = new JTextField();
    JTextField rkMedicineID = new JTextField();
    JTextField rktxtDate = new JTextField();
    JTextField rktxtExpDate = new JTextField();
    JTextField rktxtBillNo = new JTextField();
    Map<Object, Object> rkbillItem = new HashMap<>();
}
